import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { PGlite } from '@electric-sql/pglite';

const resetScript = readFileSync(
  new URL('../supabase/scripts/reset_all_test_transactions.sql', import.meta.url),
  'utf8',
);

const truncateStatement = resetScript.match(/truncate table[\s\S]*?restart identity;/i)?.[0];

test('transaction reset truncates every table in the restricted FK graph', async (t) => {
  assert.ok(truncateStatement, 'reset script must contain one TRUNCATE ... RESTART IDENTITY statement');

  const db = new PGlite();
  t.after(() => db.close());

  const transactionTables = [...truncateStatement.matchAll(/public\.([a-z_]+)/g)].map(
    ([, tableName]) => tableName,
  );
  const financialTables = new Set([
    'payment_allocation_changes',
    'refund_obligations',
    'refund_settlements',
    'delivery_charge_adjustments',
    'delivery_adjustment_items',
    'payment_receipt_snapshots',
    'payments',
    'credit_due_date_requests',
    'collection_run_credit_charges',
    'delivery_charges',
    'collection_runs',
  ]);

  for (const tableName of transactionTables) {
    if (!financialTables.has(tableName)) {
      await db.exec(`create table public.${tableName} (id bigint generated by default as identity primary key)`);
    }
  }

  await db.exec(`
    create table public.collection_runs (
      id bigint generated by default as identity primary key
    );
    create table public.delivery_charges (
      id bigint generated by default as identity primary key
    );
    create table public.payments (
      id bigint generated by default as identity primary key
    );
    create table public.payment_receipt_snapshots (
      payment_id bigint primary key references public.payments(id) on delete restrict
    );
    create table public.payment_allocation_changes (
      id bigint generated by default as identity primary key,
      payment_id bigint not null references public.payments(id) on delete restrict,
      charge_id bigint not null references public.delivery_charges(id) on delete restrict
    );
    create table public.refund_obligations (
      id bigint generated by default as identity primary key,
      payment_id bigint not null references public.payments(id) on delete restrict,
      charge_id bigint not null references public.delivery_charges(id) on delete restrict
    );
    create table public.refund_settlements (
      id bigint generated by default as identity primary key,
      obligation_id bigint not null references public.refund_obligations(id) on delete restrict
    );
    create table public.delivery_charge_adjustments (
      id bigint generated by default as identity primary key,
      charge_id bigint not null references public.delivery_charges(id) on delete restrict
    );
    create table public.delivery_adjustment_items (
      id bigint generated by default as identity primary key,
      adjustment_id bigint not null references public.delivery_charge_adjustments(id) on delete restrict
    );
    create table public.credit_due_date_requests (
      id bigint generated by default as identity primary key,
      charge_id bigint not null references public.delivery_charges(id) on delete restrict
    );
    create table public.collection_run_credit_charges (
      collection_run_id bigint not null references public.collection_runs(id) on delete restrict,
      charge_id bigint not null references public.delivery_charges(id) on delete restrict,
      primary key (collection_run_id, charge_id)
    );

    insert into public.collection_runs default values;
    insert into public.delivery_charges default values;
    insert into public.payments default values;
    insert into public.payment_receipt_snapshots values (1);
    insert into public.payment_allocation_changes (payment_id, charge_id) values (1, 1);
    insert into public.refund_obligations (payment_id, charge_id) values (1, 1);
    insert into public.refund_settlements (obligation_id) values (1);
    insert into public.delivery_charge_adjustments (charge_id) values (1);
    insert into public.delivery_adjustment_items (adjustment_id) values (1);
    insert into public.credit_due_date_requests (charge_id) values (1);
    insert into public.collection_run_credit_charges values (1, 1);
  `);

  await db.exec(truncateStatement);

  for (const tableName of [
    'payment_allocation_changes',
    'refund_obligations',
    'refund_settlements',
    'delivery_charge_adjustments',
    'delivery_adjustment_items',
    'payment_receipt_snapshots',
    'payments',
    'credit_due_date_requests',
    'collection_run_credit_charges',
    'delivery_charges',
    'collection_runs',
  ]) {
    const result = await db.query(`select count(*)::integer as count from public.${tableName}`);
    assert.equal(result.rows[0].count, 0, `${tableName} should be empty after reset`);
  }
});
